# -*- coding: utf-8 -*-
"""Project Final 07032023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iqXtm-qF1yfzEMkxjU3sCdMeW66yT6vD
"""

import streamlit as st
import pandas as pd
from sklearn import datasets
from sklearn.linear_model import LinearRegression

st.write("""
# Sales Prediction App

This app predicts the **Sales** type!
""")

st.sidebar.header('User Input Parameters')

def user_input_features():
    TV = st.sidebar.slider('TV', 0, 200, 10)
    Radio = st.sidebar.slider('Radio', 0, 100, 10)
    Newspaper = st.sidebar.slider('Newspaper', 0, 100, 10)
    data = {'TV': TV,
            'Radio': Radio,
            'Newspaper': Newspaper}
    features = pd.DataFrame(data, index=[0])
    return features

df = user_input_features()

st.subheader('User Input parameters')
st.write(df)

df = pd.read_csv('/content/Advertising - Advertising.csv')
df = df.drop(['Unnamed: 0'], axis=1)
x = df.drop('Sales', axis=1)  
y = df['Sales']


clf = LinearRegression()
clf.fit(x, y)

prediction = clf.predict(df)
prediction_proba = clf.predict_proba(df)

st.subheader('Prediction')
st.write(prediction)